package com.socialquantum.w.gtkpgtpkogtkpotg

object KODokok {
    var gtitghugt: String = "link"
    var nhyjiohyiohy5: String = "apps"
    var ghgtgt59: String? = "main_id"
    val rjgtjogtjjgtjtgjjgt = "tdb2"
    val gtgthtghgthugt: String = "country"
    val codeCodegtgt: String = "uff"
    val onegtgt = "deviceID="
    val vbfbbrfgfrggrffr = "sub_id_1="
    val vfbhbfryurfgrfrf = "ad_id="
    val gt2hyhyhy = "sub_id_4="
    val vbfbfrrfhrfhfrhfrfr = "sub_id_5="
    val hy6hy59hy = "sub_id_6="
    val gthyhjyhyjuuj = "naming"
    val trolologttggt = "deeporg"
    const val vfbrfgfrgrfgrfgyrfgy = "670d10b5-4427-41be-8510-1d832e70e188"
    val bngjgtitghgtg = "78528126370524433959"
    val hy5hy95h = "com.socialquantum.w"
    val gtjjgtjgtjgtjt = "vk5rtzne6CYzfcbcwQbvSP"
    val hy59hy59hy59hy: String = "myID"
    var instIdgttg: String? = "instID"
    var bngjgthgthtghgt: String = "link"
}